| Experience (Years) | Education | Salary |
|--------------------|-----------|--------|
| 4                  | BE        | 50k    |
| 6                  | PhD       | 100k   |
| 3                  | Masters   | 80k    |
| 6                  | PhD       | 120k   |

Experience and Education are input or independent fetures and Salary is output or dependent feature.

Education is categorical feature. If we give the education as it is then model can't understand the data.

The main aim of data encoding is to convert categorical feature into a numberical feature so that ml model can be trained.

Types of Data Encoding
- One Hot Encoding
- Label Encoding
- Ordinal Encoding
- Target Guided Ordinal Encoding

1) Nominal or OHE (No specific order or rank)

House Price Prediction

## Property Listing

| **No. of Rooms** | **House Size (sq ft)** | **Location**        | **Price (NPR)**  |
|------------------|------------------------|---------------------|------------------|
|                  |                        | Kathmandu           |                  |
|                  |                        | Bhaktapur           |                  |
|                  |                        | Lalitpur            |                  |
|                  |                        | Kathmandu           |                  |
|                  |                        | Bhaktapur           |                  |
|                  |                        | Lalitpur            |                  |

Location (Kathmandu, Bhaktapur, Lalitpur)

Location --> OHE

## Property Listing

| **No. of Rooms** | **House Size (sq ft)** | **Location**        | **Price (NPR)**  | **Kathmandu** | **Bhaktapur** | **Lalitpur** |
|------------------|------------------------|---------------------|------------------|---------------|---------------|--------------|
|                  |                        | Kathmandu           |                  | 1             | 0             | 0            |
|                  |                        | Bhaktapur           |                  | 0             | 1             | 0            |
|                  |                        | Lalitpur            |                  | 0             | 0             | 1            |
|                  |                        | Kathmandu           |                  | 1             | 0             | 0            |
|                  |                        | Bhaktapur           |                  | 0             | 1             | 0            |
|                  |                        | Lalitpur            |                  | 0             | 0             | 1            |

Disadvantage:
- Creates sparse matrix.(10 locations only takes 1 and 0 which leads to overfitting)
- 1000 categories (100 features) . No of features increased , performance of model decreases

In [1]:
# import pandas and one hot encoder
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
# create a dataframe with a single column of color categories
df = pd.DataFrame({
    'color': ['red', 'blue', 'green', 'green', 'blue', 'red']
})

In [3]:
df

   color
0    red
1   blue
2  green
3  green
4   blue
5    red

In [4]:
type(df)

pandas.core.frame.DataFrame

In [5]:
df.dtypes

color    object
dtype: object

In [6]:
## Create an instance of the OneHotEncoder
ohe = OneHotEncoder()
ohe

OneHotEncoder()

In [7]:
ohe.fit_transform(df[['color']]).toarray()
ohe

OneHotEncoder()

In [8]:
# df = df.rename(columns = {'color':'colors'})
# df

In [9]:
df['color']

0      red
1     blue
2    green
3    green
4     blue
5      red
Name: color, dtype: object

In [10]:
ohe.fit_transform(df[['color']]).toarray()

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [11]:
# fit the encoder to the dataframe and transform the categorical variable
encoded = ohe.fit_transform(df[['color']]).toarray()

In [12]:
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [13]:
ohe.get_feature_names_out(['color'])

array(['color_blue', 'color_green', 'color_red'], dtype=object)

In [14]:
encoded_df = pd.DataFrame(
    encoded,
    columns=ohe.get_feature_names_out(['color'])
    )

In [15]:
df['color']

0      red
1     blue
2    green
3    green
4     blue
5      red
Name: color, dtype: object

In [16]:
encoded_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         1.0          0.0        0.0
5         0.0          0.0        1.0

In [17]:
df

   color
0    red
1   blue
2  green
3  green
4   blue
5    red

In [18]:
pd.concat([df, encoded_df])

   color  color_blue  color_green  color_red
0    red         NaN          NaN        NaN
1   blue         NaN          NaN        NaN
2  green         NaN          NaN        NaN
3  green         NaN          NaN        NaN
4   blue         NaN          NaN        NaN
5    red         NaN          NaN        NaN
0    NaN         0.0          0.0        1.0
1    NaN         1.0          0.0        0.0
2    NaN         0.0          1.0        0.0
3    NaN         0.0          1.0        0.0
4    NaN         1.0          0.0        0.0
5    NaN         0.0          0.0        1.0

In [19]:
pd.concat([df, encoded_df], axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4   blue         1.0          0.0        0.0
5    red         0.0          0.0        1.0

In [20]:
import seaborn as sns
df = sns.load_dataset('tips')

In [21]:
df.shape

(244, 7)

In [22]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [23]:
df.dtypes

total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
dtype: object

In [24]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [25]:
encoder = OneHotEncoder()

In [26]:
encoder.fit_transform(df[['time']]).toarray()

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [27]:
encoded = encoder.fit_transform(df[['time']]).toarray()

In [28]:
encoded

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [29]:
df.sample(10)

     total_bill   tip     sex smoker   day    time  size
119       24.08  2.92  Female     No  Thur   Lunch     4
224       13.42  1.58    Male    Yes   Fri   Lunch     2
207       38.73  3.00    Male    Yes   Sat  Dinner     4
157       25.00  3.75  Female     No   Sun  Dinner     4
242       17.82  1.75    Male     No   Sat  Dinner     2
192       28.44  2.56    Male    Yes  Thur   Lunch     2
135        8.51  1.25  Female     No  Thur   Lunch     2
179       34.63  3.55    Male    Yes   Sun  Dinner     2
86        13.03  2.00    Male     No  Thur   Lunch     2
67         3.07  1.00  Female    Yes   Sat  Dinner     1

In [30]:
encoded_df = pd.DataFrame(
    encoded,
    columns=encoder.get_feature_names_out(['time'])
)

In [31]:
encoded_df.sample(10)

     time_Dinner  time_Lunch
150          1.0         0.0
211          1.0         0.0
0            1.0         0.0
139          0.0         1.0
166          1.0         0.0
120          0.0         1.0
51           1.0         0.0
131          0.0         1.0
56           1.0         0.0
9            1.0         0.0

In [32]:
final_df = pd.concat([df, encoded_df], axis=1)
final_df.sample(10)

,total_bill,tip,sex,smoker,day,time,size,time_Dinner,time_Lunch
221,13.42,3.48,Female,Yes,Fri,Lunch,2,0.0,1.0
108,18.24,3.76,Male,No,Sat,Dinner,2,1.0,0.0
131,20.27,2.83,Female,No,Thur,Lunch,2,0.0,1.0
42,13.94,3.06,Male,No,Sun,Dinner,2,1.0,0.0
197,43.11,5.00,Female,Yes,Thur,Lunch,4,0.0,1.0
129,22.82,2.18,Male,No,Thur,Lunch,3,0.0,1.0
170,50.81,10.00,Male,Yes,Sat,Dinner,3,1.0,0.0
109,14.31,4.00,Female,Yes,Sat,Dinner,2,1.0,0.0
41,17.46,2.54,Male,No,Sun,Dinner,2,1.0,0.0
56,38.01,3.00,Male,Yes,Sat,Dinner,4,1.0,0.0

Label and Ordinal Encoding

In [33]:
from sklearn.preprocessing import LabelEncoder

In [34]:
df = pd.DataFrame({
    'color': ['red', 'blue', 'green', 'green', 'blue', 'red']
})

In [35]:
df

   color
0    red
1   blue
2  green
3  green
4   blue
5    red

In [36]:
le = LabelEncoder()
le.fit_transform(df['color'])

array([2, 0, 1, 1, 0, 2])

In [37]:
size = ['small', 'medium', 'large', 'medium', 'small', 'large']
le.fit_transform(size)

array([2, 1, 0, 1, 2, 0])

In [38]:
df['color']

0      red
1     blue
2    green
3    green
4     blue
5      red
Name: color, dtype: object

In [39]:
le.fit_transform(df['color'])

array([2, 0, 1, 1, 0, 2])

In [40]:
df['color'] = le.fit_transform(df['color'])
df

   color
0      2
1      0
2      1
3      1
4      0
5      2

Problem : ML algorithm assumes one is greater than another.

In [41]:
from sklearn.preprocessing import OrdinalEncoder

In [42]:
df2 = pd.DataFrame({
    'size' : ['small', 'medium', 'large', 'medium', 'small', 'large']
})

In [43]:
# Create an instance of the OrdinalEncoder class and fit transform the dataframe
encoder = OrdinalEncoder(categories=[['small', 'medium', 'large']])

In [44]:
df2['size'] = encoder.fit_transform(df2[['size']])
df2

   size
0   0.0
1   1.0
2   2.0
3   1.0
4   0.0
5   2.0

In [45]:
df2[['size']]

   size
0   0.0
1   1.0
2   2.0
3   1.0
4   0.0
5   2.0

In [46]:
le = LabelEncoder()
le.fit_transform(df2[['size']])

c:\Users\acer\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([0, 1, 2, 1, 0, 2])

Target Guided Ordinal Encoding
- It is a technique used to encode categorical variables based on their relationship with target variable.
- We replace each category in the categorical variable with a numerical value based on the mean or median of the target variable of that category.

In [47]:
df = pd.DataFrame({
    'city': ['New York', 'London', 'Paris', 'Tokyo', 'New York', 'Paris'],
    'price': [200, 150, 300, 250, 180, 320]
})

In [48]:
df

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    320

In [49]:
df.groupby('city')

In [50]:
df.groupby('city')['price']

In [51]:
# calculate the mean price for each city
df.groupby('city')['price'].mean()

city
London      150.0
New York    190.0
Paris       310.0
Tokyo       250.0
Name: price, dtype: float64

In [52]:
type(df.groupby('city')['price'].mean())

pandas.core.series.Series

In [53]:
df.groupby('city')['price'].mean().to_dict()

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [54]:
mean_price = df.groupby('city')['price'].mean().to_dict()
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [55]:
df.head()

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180

In [56]:
df['city_encoded'] = df['city'].map(mean_price) # map replaces each city name in df['city'] with its corresponding mean price from the dictionary

In [57]:
df

       city  price  city_encoded
0  New York    200         190.0
1    London    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New York    180         190.0
5     Paris    320         310.0

In [58]:
df['city'] = df['city'].map(mean_price) 
df

    city  price  city_encoded
0  190.0    200         190.0
1  150.0    150         150.0
2  310.0    300         310.0
3  250.0    250         250.0
4  190.0    180         190.0
5  310.0    320         310.0